{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lldap-chart.fullname" . }}-data
  namespace: {{ .Values.namespace }}
  labels:
    app: lldap
    {{- include "lldap-chart.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
{{- end }}
{{- if and .Values.persistence.enabled .Values.persistence.manualProvision }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "lldap-chart.fullname" . }}-data-pv
  namespace: {{ .Values.namespace }}
  labels:
    app: lldap
    {{- include "lldap-chart.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.storageSize }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  {{- if .Values.persistence.localPath }}
  hostPath:
    path: {{ .Values.persistence.localPath }}
  {{- end }}
{{- end }}