{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lldap-chart.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "lldap-chart.labels" . | nindent 4 }}
type: Opaque
data:
  lldap-jwt-secret: {{ required "secret.lldapJwtSecret is required" .Values.secret.lldapJwtSecret | b64enc }}
  lldap-ldap-user-name: {{ .Values.secret.lldapUserName | b64enc }}
  lldap-ldap-user-pass: {{ required "secret.lldapUserPass is required" .Values.secret.lldapUserPass | b64enc }}
  base-dn: {{ .Values.secret.lldapBaseDn | b64enc }}
{{- end }}
