apiVersion: v1
kind: Service
metadata:
  name: {{ include "lldap.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lldap.labels" . | nindent 4 }}
  annotations:
    lldap: https://github.com/nitnelave/lldap
    k8s: https://github.com/Evantage-WS/lldap-kubernetes
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "lldap.selectorLabels" . | nindent 4 }}
